config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  root to: "pages#home"

  get "/design", to: "pages#design"
  get "/basket", to: "pages#basket"
  get "/paymentdone", to: "pages#paymentdone"

  get "/styles", to: "presets#styles"
  get "/presets", to: "presets#presets"

  resources :customs, only: [:index, :show, :new, :create]


  resources :bookings, only: [:show, :update] do
    resources :chatrooms, only: [:create]
  end

  resources :chatrooms, only: [:new, :show] do
    resources :messages, only: :create
  end


  get "/user_dashboard", to: "customs#user_dashboard"
  get "/designer_dashboard", to: "customs#designer_dashboard"








  get "/booking/3/model", to: "customs#model"
  get "/booking/3/model/checkout", to: "customs#model_checkout"
  get "/booking/3/spec", to: "customs#spec"






  # resources :bookings, only: [:show] do
  #   resources :model, only: [:show]
  # end

  # resources :designers do
  #   resources :customs, only: [:index, :new, :create]
  # end

  # resources :customs, only: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :designer
  has_one :designer_model
  has_one_attached :spec_file


end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :user
  belongs_to :designer
  has_many :messages
end

app/models/designer.rb
class Designer < ApplicationRecord
  has_many :bookings
  has_many :designer_models
  belongs_to :user

  has_many_attached :project_photos

  has_many :chatrooms

end

app/models/designer_item.rb
class DesignerItem < ApplicationRecord
  belongs_to :designer_model
  has_one_attached :image
end

app/models/designer_model.rb
class DesignerModel < ApplicationRecord
  belongs_to :booking
  belongs_to :designer
  has_one_attached :model
  has_many :designer_items
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :preset_items
  #belongs_to :preset, through: :preset_items
  validates :name, presence: true, length: { maximum: 50 }
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :description, presence: true, length: { maximum: 1000 }

  has_one_attached :photo
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user

  def sender?(a_user)
    user.id == a_user.id
  end
end

app/models/preset.rb
class Preset < ApplicationRecord
  has_many :preset_items
  has_many :items, through: :preset_items

  has_one_attached :photo
end

app/models/preset_item.rb
class PresetItem < ApplicationRecord
  belongs_to :preset
  belongs_to :item

  # validates :
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true, length: { maximum: 20 }
  validates :last_name, presence: true, length: { maximum: 50 }

  has_many :designer_models, through: :designer

  has_one_attached :avatar
  has_one :cart

  has_many :bookings

  has_one :designer

  has_many :chatrooms
  has_many :messages

  def designer?
    !designer.nil?
  end
end

# Path: app/controllers/application_controller.rb

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def update
    booking = Booking.find(params[:id])
    booking.status = params[:status]
    booking.save
    redirect_to designer_dashboard_path
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def new

  end

  def create
    @booking = Booking.find(params[:booking_id])
    @chatroom = Chatroom.create({
      user_id: current_user.id,
      designer_id: @booking.designer.id,
    })
    redirect_to chatroom_path(@chatroom)
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
    @chat_with_user = @chatroom.user == current_user ? @chatroom.designer.user : @chatroom.user
  end
end

app/controllers/customs_controller.rb
class CustomsController < ApplicationController


  # show all designers page
  def index
    @designers = Designer.all
  end

  def show
    @designer = Designer.find(params[:id])
  end


  # form to create booking
  def new
    @designer = Designer.find(params[:format])
    @booking = Booking.new
  end

 #save booking
  def create
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id
    @booking.designer_id = params[:designer]
    @booking.status = "designing"
    @booking.save
    redirect_to user_dashboard_path
  end

  def user_dashboard
    @bookings = Booking.where(user_id: current_user.id)
  end

  def designer_dashboard
    @bookings = Booking.where(designer_id: current_user.designer.id)
  end

  def model
  end

  def model_checkout

  end

  def spec

  end
  private
  def booking_params
    params.require(:booking).permit(:spec_text, :spec_file, :designer)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user

    if @message.save
      # redirect_to chatroom_path(@chatroom)

      ChatroomChannel.broadcast_to(
        @chatroom,
        message: render_to_string(partial: "message", locals: { message: @message }),
        sender_id: @message.user.id
      )
      head :ok
    else
      render "chatrooms/show", status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  # beautiful landing page, has link to #design page
  def home
  end

  # promts user to choose between custom and preset designs
  def design
  end

  # contains items added by the user
  def basket
    @cart = current_user.cart || Cart.create(user_id: current_user.id)
    params.delete(:controller)
    params.delete(:action)
    cart_items = []
    params.each do | key, value|
      cart_items << CartItem.create!(cart_id: @cart.id, quantity: value.to_i, item_id: Item.find(key.to_i).id)
    end
    @cart_items = cart_items.reject {|cart_item| cart_item.quantity == 0}
  end

  def paymentdone

  end

  def custom

  end

end

app/controllers/presets_controller.rb
class PresetsController < ApplicationController

  # landing page if user selected preset designs. Promts user to choose deisgn style and room type.
  # is a form in disquise
  def styles
  end

  # display presets matched from the #styles form
  def presets
    if params[:style].present? && params[:room].present?
      sql_query = "style ILIKE :style AND room ILIKE :room"
      @presets = Preset.where(sql_query, style: "%#{params[:style]}%", room: "%#{params[:room]}%")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/customs/designer_dashboard.html.erb
<div class="container">
    <h1>Bookings</h1>
    <% if @bookings.empty? %>
      <h1>You don't have any bookings yet!</h1>
    <% else %>
      <div class="booking-item"  style="background-color: #d7d7d9;">
        <p class="p-class">Client</p>
        <p class="p-class content-place">Booked on</p>
        <p class="p-class content-place">Status</p>
        <p class="p-class content-place"> </p>
      </div>

      <% @bookings.each do |booking| %>

        <div class="booking-item">

          <div class="p-class dashboard-avatar">

              <% if booking.user.avatar.key.nil?%>
                  <%= image_tag "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1180&q=80", height: 41, width: 50, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
                <%= cl_image_tag booking.user.avatar.key, height: 41, width: 50, crop: :fill, class: "avatar dropdown-toggle" %>
              <% end %>

              <div class="designer-name-dashboard">
                <%= booking.user.first_name %>
              </div>

          </div>

          <div class="p-class content-place">
          <%= booking.created_at.strftime("%B %d, %Y") %>
          </div>


          <div class="p-class content-place">
            <p class=" content-place status-<%= booking.status %>"><%= booking.status %></p>
          </div>

          <div class="p-class content-place">
            <% if Chatroom.find_by(user_id: booking.user.id, designer_id: current_user.designer.id) %>
              <div><%= link_to chatroom_path(Chatroom.find_by(user_id: booking.user.id, designer_id: current_user.designer.id)), class: "buttn-red-log-in" do %>
                <i class="fa-regular fa-comment-dots content-place dashboard-icon"></i>
                <% end %>
              </div>
            <% else %>
              <div><%= link_to booking_chatrooms_path(booking), data: { turbo_method: :post }, class: "butten-red-log-in" do %>
                <i class="fa-regular fa-comment-dots content-place dashboard-icon" ></i>
                <% end%>
              </div>
            <% end %>

            <div>
              <%= link_to booking_3_model_path do %>
                <i class="fa-solid fa-cube dashboard-icons dashboard-icon"></i>
              <% end%>
            </div>

            <div class="p-class content-place">

              <% if booking.status == "designing"%>
                <div>
                  <%= link_to booking_path(booking.id, status: "completed"), data: {turbo_method: :put} do %>
                    <i class="fa-solid fa-square-check content-place dashboard-icon"></i>
                  <% end %>
                </div>

                <div>
                  <%= link_to booking_path(booking.id, status: "declined"), data: {turbo_method: :put}, class: " btn-danger" do %>
                    <i class="fa-regular fa-circle-xmark content-place dashboard-icon"></i>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>

        </div>

      <% end %>
    <% end %>
</div>

app/views/customs/index.html.erb
<div class="container mt-4 p-0">
    <h1 mt-4>Our Designers</h1>

    <div class="row compensation-margins-designers-container">
      <% @designers.each do |designer| %>
        <div class="col-12 col-lg-4">
          <div class="designers-card">
            <div class="designer-avatar-name-container">
              <div class="designers-card-avatar">
                <%= cl_image_tag designer.user.avatar.key, crop: :fill  %>
              </div>

              <div class="designers-card-name">
                <h2><%= designer.user.first_name %> </h2>
                <h2><%= designer.user.last_name %></h2>
              </div>
            </div>

            <div class="designers-page-bio">
              <p><%= designer.bio %></p>
            </div>

            <div class="designers-card-projects-container">
              <% designer.project_photos.first(2).each do |photo| %>
                <div class="designers-card-projects">
                  <%=cl_image_tag photo.key, height: 800, width: 800, crop: :fill  %>
                </div>
              <% end %>
            </div>
            <div class="designers-card-btn-container d-flex justify-content-center">
                <%= link_to "Show more", custom_path(designer), class: "designers-card-sumbit-button button" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/customs/model_checkout.html.erb
<div class="container">
  <div class="row mt-5">

    <h1 class="px-0 pb-2">Payment</h1>

      <div class="col payment-right me-2">
          <h2 class="ms-2">Order Summary</h2 clas="ms-5">

                    <div class="preset-items pe-2">

                      <div class="d-flex item-card align-items-center mb-2 mx-2">
                        <div class="model-image-container">
                        <img src="https://res.cloudinary.com/dxgkclowd/image/upload/v1678848440/3153hc-1_sv3rxl.jpg" alt="" class="model-item-image">
                        </div>
                        <p class="mt-3 me-5 ps-2">
                        <span class="template-item-name">Copper lamp</span>
                        <br>
                        <span class="template-item-description">Will brighten up any living room</span>
                        </p>
                        <div class="cart-input ms-auto me-5 mb-3 d-flex flex-column">
                        <div class="d-flex">
                        <span>x4</span>
                        </div>
                        <p class="item-price">$ <span data-total-price-target="unitprice" class="item-price">80</span></p>
                        </div>
                      </div>

                      <div class="d-flex item-card align-items-center mb-2 mx-2">
                        <div class="model-image-container">
                        <img src="https://res.cloudinary.com/dxgkclowd/image/upload/v1678845453/1525590_jl3ech.jpg" alt="" class="model-item-image">
                        </div>
                        <p class="mt-3 me-5 ps-2">
                        <span class="template-item-name">White leather sofa</span>
                        <br>
                        <span class="template-item-description">Very soft and spacious</span>
                        </p>
                        <div class="cart-input ms-auto me-5 mb-3 d-flex flex-column">
                        <div class="d-flex">
                        <span>x1</span>
                        </div>
                        <p class="item-price">$ <span data-total-price-target="unitprice" class="item-price">800</span></p>
                        </div>
                      </div>

                      <div class="d-flex item-card align-items-center mb-2 mx-2">
                        <div class="model-image-container">
                        <img src="https://res.cloudinary.com/dxgkclowd/image/upload/v1678845484/oro-polished-silver-bar-stool_b7vqml.jpg" alt="" class="model-item-image">
                        </div>
                        <p class="mt-3 me-5 ps-2">
                        <span class="template-item-name">Silver chair</span>
                        <br>
                        <span class="template-item-description">Modern chair for modern kitchen</span>
                        </p>
                        <div class="cart-input ms-auto me-5 mb-3 d-flex flex-column">
                        <div class="d-flex">
                        <span>x3</span>
                        </div>
                        <p class="item-price">$ <span data-total-price-target="unitprice" class="item-price">170</span></p>
                        </div>
                      </div>

                      <div class="d-flex item-card align-items-center mb-2 mx-2">
                        <div class="model-image-container">
                        <img src="https://res.cloudinary.com/dxgkclowd/image/upload/v1678845517/getimage.ashx_wmwwap.jpg" alt="" class="model-item-image">
                        </div>
                        <p class="mt-3 me-5 ps-2">
                        <span class="template-item-name">Oak floor</span>
                        <br>
                        <span class="template-item-description">Long lasting</span>
                        </p>
                        <div class="cart-input ms-auto me-5 mb-3 d-flex flex-column">
                        <div class="d-flex">
                        <span>40m2</span>
                        </div>
                        <p class="item-price">$ <span data-total-price-target="unitprice" class="item-price">40</span></p>
                        </div>
                      </div>

                      <div class="d-flex item-card align-items-center mb-2 mx-2">
                        <div class="model-image-container">
                        <img src="https://res.cloudinary.com/dxgkclowd/image/upload/v1678846073/IMG_4503-400x500_imvoji.jpg" alt="" class="model-item-image">
                        </div>
                        <p class="mt-3 me-5 ps-2">
                        <span class="template-item-name">Pillow Africa</span>
                        <br>
                        <span class="template-item-description">Hand crafted</span>
                        </p>
                        <div class="cart-input ms-auto me-5 mb-3 d-flex flex-column">
                        <div class="d-flex">
                        <span>x4</span>
                        </div>
                        <p class="item-price">$ <span data-total-price-target="unitprice" class="item-price">120</span></p>
                        </div>
                      </div>

                      <div class="d-flex item-card align-items-center mb-2 mx-2">
                        <div class="model-image-container">
                        <img src="https://res.cloudinary.com/dxgkclowd/image/upload/v1678846131/rh-150-vi_mvu7f9.jpg" alt="" class="model-item-image">
                        </div>
                        <p class="mt-3 me-5 ps-2">
                        <span class="template-item-name">Coppper Faucet</span>
                        <br>
                        <span class="template-item-description">Purifies tap water</span>
                        </p>
                        <div class="cart-input ms-auto me-5 mb-3 d-flex flex-column">
                        <div class="d-flex">
                        <span>x1</span>
                        </div>
                        <p class="item-price">$ <span data-total-price-target="unitprice" class="item-price">300</span></p>
                        </div>
                      </div>

                      <div class="d-flex item-card align-items-center mb-2 mx-2">
                        <div class="model-image-container">
                        <img src="https://res.cloudinary.com/dxgkclowd/image/upload/v1678846191/painting_720_kynmdn.jpg" alt="" class="model-item-image">
                        </div>
                        <p class="mt-3 me-5 ps-2">
                        <span class="template-item-name">Modern painting</span>
                        <br>
                        <span class="template-item-description">Modern art</span>
                        </p>
                        <div class="cart-input ms-auto me-5 mb-3 d-flex flex-column">
                        <div class="d-flex">
                        <span>x1</span>
                        </div>
                        <p class="item-price">$ <span data-total-price-target="unitprice" class="item-price">30</span></p>
                        </div>
                      </div>

                      <div class="d-flex item-card align-items-center mb-2 mx-2">
                        <div class="model-image-container">
                        <img src="https://res.cloudinary.com/dxgkclowd/image/upload/v1678846556/coffee-table_720_re78ug.jpg" alt="" class="model-item-image">
                        </div>
                        <p class="mt-3 me-5 ps-2">
                        <span class="template-item-name">Brown marble coffee table</span>
                        <br>
                        <span class="template-item-description">Hides coffee stains</span>
                        </p>
                        <div class="cart-input ms-auto me-5 mb-3 d-flex flex-column">
                        <div class="d-flex">
                        <span>x1</span>
                        </div>
                        <p class="item-price">$ <span data-total-price-target="unitprice" class="item-price">420</span></p>
                        </div>
                      </div>

                      <div class="d-flex item-card align-items-center mb-2 mx-2">
                        <div class="model-image-container">
                        <img src="https://res.cloudinary.com/dxgkclowd/image/upload/v1678846559/plant_720_xmf9eu.jpg" alt="" class="model-item-image">
                        </div>
                        <p class="mt-3 me-5 ps-2">
                        <span class="template-item-name">Flower pot 1</span>
                        <br>
                        <span class="template-item-description">Holds a meduim plant</span>
                        </p>
                        <div class="cart-input ms-auto me-5 mb-3 d-flex flex-column">
                        <div class="d-flex">
                        <span>x2</span>
                        </div>
                        <p class="item-price">$ <span data-total-price-target="unitprice" class="item-price">30</span></p>
                        </div>
                      </div>

                      <div class="d-flex item-card align-items-center mb-2 mx-2">
                        <div class="model-image-container">
                        <img src="https://res.cloudinary.com/dxgkclowd/image/upload/v1678846560/vase_720_gau4dm.jpg" alt="" class="model-item-image">
                        </div>
                        <p class="mt-3 me-5 ps-2">
                        <span class="template-item-name">Flower pot 2</span>
                        <br>
                        <span class="template-item-description">Holds a small plant</span>
                        </p>
                        <div class="cart-input ms-auto me-5 mb-3 d-flex flex-column">
                        <div class="d-flex">
                        <span>x4</span>
                        </div>
                        <p class="item-price">$ <span data-total-price-target="unitprice" class="item-price">20</span></p>
                        </div>
                      </div>

                      <div class="d-flex item-card align-items-center mb-2 mx-2">
                        <div class="model-image-container">
                        <img src="https://res.cloudinary.com/dxgkclowd/image/upload/v1678846649/1400955805266_y3zloq.jpg" alt="" class="model-item-image">
                        </div>
                        <p class="mt-3 me-5 ps-2">
                        <span class="template-item-name">Kitchen table</span>
                        <br>
                        <span class="template-item-description">Used as kitchen island</span>
                        </p>
                        <div class="cart-input ms-auto me-5 mb-3 d-flex flex-column">
                        <div class="d-flex">
                        <span>x1</span>
                        </div>
                        <p class="item-price">$ <span data-total-price-target="unitprice" class="item-price">860</span></p>
                        </div>
                      </div>
                    </div>
            <p class="payment-total">Your total is $3420</p>
      </div>
      <div class="col-12 col-lg-6 mb-5 order-1 order-lg-2 d-flex ps-2 pe-0">
          <div class="box1">
            <div>
              <h3>Payment</h3>
              <div class="icons">
                <img src="https://img.icons8.com/color/48/000000/visa.png"/>
                <img src="https://img.icons8.com/color/48/000000/mastercard-logo.png"/>
                <img src="https://img.icons8.com/color/48/000000/maestro.png"/>
              </div>


              <form class="mt-4">
                <div>
                  <span>Cardholder's name:</span>
                  <input class="pay-fild" placeholder="Linda Williams">
                  <span>Card Number:</span>
                  <input class="pay-fild" placeholder="0125 6780 4567 9909">
                  <div class="row">
                    <div class="col-4 expiry-date">
                      <span>Expiry date:</span>
                      <input class="pay-fild" placeholder="YY/MM">
                    </div>
                    <div class="col-4">
                      <span>CVV:</span>
                      <input class="pay-fild" id="cvv">
                    </div>
                  </div>
                  <div>
                    <input class="pay-fild" type="checkbox" id="save_card" class="align-left">
                    <label for="save_card">Save card details to wallet</label>
                  </div>
                </div>
                  <div>
                  <div class="d-flex flex-column justify-content-end vh-20">
                    <%= link_to "Confirm payment", paymentdone_path, class: "button button-div-basket" %>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>


  </div>
</div>

app/views/customs/new.html.erb
<div class="container p-0">

  <div class="row mt-4 p-0 d-flex justify-content-center align-items-center">
    <div class="col-lg-6 col-12">
     <h1>Upload your Information</h1>
    </div>
      <div class="col-lg-6 col-12 d-flex align-items-center" style="height: 85vh;">
        <div class="new-booking-form-container ">

          <%= simple_form_for @booking, url: customs_path(designer: @designer) do |f| %>
            <%= f.input :spec_file, as: :file %>
            <%= f.input :spec_text,:input_html => { 'rows' => 10, 'cols' => 10 } %>
              <p> Please fill in the form as detailed as possible.
                Provide your room dimensions, furnitures, and any other information that you think is relevant.
                We will get back to you as soon as possible.
                For the full experience, please upload a floor plan of your room, or even a LIDAR scan of your room!
              </p>
              </br>
            <%= f.submit class: "button"%>
          <% end %>
        </div>
      </div>
  </div>
</div>

app/views/customs/show.html.erb
<div class="container p-0 mt-4 height-100-percent">
    <div class="row height-100-percent">
        <div class="col-12 p-0 height-100-percent">
          <div class="designers-show height-100-percent">
            <div class="row m-0 height-100-percent">
              <div class="col-lg-3 col-12 ps-0">
                <div class="designer-show-left">
                  <div class="designers-show-avatar">
                    <%= cl_image_tag @designer.user.avatar.key, height: 200, width: 200, crop: :fill  %>
                  </div>

                  <div class="designers-show-name">
                    <h2><%= @designer.user.first_name %> <%= @designer.user.last_name %> </h2>
                  </div>

                  <div>
                    <a href="#">www.interior-design.com</a>
                  </div>

                  <div class="designers-show-bio">
                    <p><%= @designer.bio %></p>
                  </div>

                  <%= link_to "Book Designer", new_custom_path(@designer), class: "designers-show-sumbit-button button"  %>

                </div>
              </div>
              <div class="col-lg-9 col-12 pe-0 height-100-percent">
                <div class="designer-show-right height-100-percent">
                  <div class="designers-show-projects-container height-100-percent">
                    <% @designer.project_photos.each do |photo| %>
                      <div class="designers-show-projects height-100-percent">
                        <%=cl_image_tag photo.key, height: 1000, width: 1000, crop: :fill  %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>

app/views/customs/user_dashboard.html.erb
<div class="container mt-4 pb-4 px-0">

    <h1>Bookings</h1>
    <% if @bookings.empty? %>
      <h1>You don't have any bookings yet!</h1>
    <% else %>
      <div class="booking-item" style="background-color: #d7d7d9;">
        <p class="p-class">Designer</p>
        <p class="p-class content-place">Booked on</p>
        <p class="p-class content-place me-45px">Status</p>
        <p class="p-class content-place"> </p>
      </div>
      <% @bookings.each do |booking| %>
        <div class="booking-item">

          <div class="p-class dashboard-avatar">
            <%= cl_image_tag booking.designer.user.avatar.key, height: 410, width: 500, crop: :fill, class: "avatar dropdown-toggle" %>

            <div class="designer-name-dashboard">
              <%= booking.designer.user.first_name %>
            </div>

          </div>

          <div class="p-class content-place booking-date">
            <%= booking.created_at.strftime("%B %d, %Y") %>
          </div>

          <div class="p-class content-place">
            <p class=" content-place status-<%= booking.status %>"><%= booking.status %></p>
          </div>


          <div class="p-class content-place booking-date">
            <% if Chatroom.find_by(user_id: current_user.id, designer_id: booking.designer.id) %>

              <div>
                <%= link_to chatroom_path(Chatroom.find_by(user_id: current_user.id, designer_id: booking.designer.id)), class: "buttn-red-log-in" do %>
                  <i class="fa-regular fa-comment-dots content-place dashboard-icon" ></i>
                <% end %>
              </div>

            <% else %>

              <div>
                <%= link_to booking_chatrooms_path(booking), data: { turbo_method: :post }, class: "butten-red-log-in" do %>
                  <i class="fa-regular fa-comment-dots content-place dashboard-icon" ></i>
                <% end%>
              </div>

            <% end %>

            <div class=" content-place ">
            <%= link_to booking_3_spec_path do %>
             <i class="fa-regular fa-file dashboard-icons dashboard-icon"></i>
            <% end %>
            </div>


            <div class="content-place">

              <% if booking.status == "completed" %>

                <%= link_to booking_3_model_path do %>
                <i class="fa-solid fa-cube dashboard-icons dashboard-icon" ></i>
                <% end%>

              <% else %>
                <i class="fa-solid fa-cube dashboard-icons dashboard-icon" style="color:#d8d8d8;"></i>
              <% end %>
            </div>

          </div>
        </div>
      <% end %>
    <% end %>
</div>