config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  root to: "pages#home"

  get "/design", to: "pages#design"
  get "/basket", to: "pages#basket"
  get "/paymentdone", to: "pages#paymentdone"

  get "/styles", to: "presets#styles"
  get "/presets", to: "presets#presets"

  resources :customs, only: [:index, :show, :new, :create]


  resources :bookings, only: [:show, :update] do
    resources :chatrooms, only: [:create]
  end

  resources :chatrooms, only: [:new, :show] do
    resources :messages, only: :create
  end


  get "/user_dashboard", to: "customs#user_dashboard"
  get "/designer_dashboard", to: "customs#designer_dashboard"








  get "/booking/3/model", to: "customs#model"
  get "/booking/3/model/checkout", to: "customs#model_checkout"
  get "/booking/3/spec", to: "customs#spec"






  # resources :bookings, only: [:show] do
  #   resources :model, only: [:show]
  # end

  # resources :designers do
  #   resources :customs, only: [:index, :new, :create]
  # end

  # resources :customs, only: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :designer
  has_one :designer_model
  has_one_attached :spec_file


end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :user
  belongs_to :designer
  has_many :messages
end

app/models/designer.rb
class Designer < ApplicationRecord
  has_many :bookings
  has_many :designer_models
  belongs_to :user

  has_many_attached :project_photos

  has_many :chatrooms

end

app/models/designer_item.rb
class DesignerItem < ApplicationRecord
  belongs_to :designer_model
  has_one_attached :image
end

app/models/designer_model.rb
class DesignerModel < ApplicationRecord
  belongs_to :booking
  belongs_to :designer
  has_one_attached :model
  has_many :designer_items
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :preset_items
  #belongs_to :preset, through: :preset_items
  validates :name, presence: true, length: { maximum: 50 }
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :description, presence: true, length: { maximum: 1000 }

  has_one_attached :photo
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user

  def sender?(a_user)
    user.id == a_user.id
  end
end

app/models/preset.rb
class Preset < ApplicationRecord
  has_many :preset_items
  has_many :items, through: :preset_items

  has_one_attached :photo
end

app/models/preset_item.rb
class PresetItem < ApplicationRecord
  belongs_to :preset
  belongs_to :item

  # validates :
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true, length: { maximum: 20 }
  validates :last_name, presence: true, length: { maximum: 50 }

  has_many :designer_models, through: :designer

  has_one_attached :avatar
  has_one :cart

  has_many :bookings

  has_one :designer

  has_many :chatrooms
  has_many :messages

  def designer?
    !designer.nil?
  end
end

# Path: app/controllers/application_controller.rb

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def update
    booking = Booking.find(params[:id])
    booking.status = params[:status]
    booking.save
    redirect_to designer_dashboard_path
  end
end

app/controllers/customs_controller.rb
class CustomsController < ApplicationController


  # show all designers page
  def index
    @designers = Designer.all
  end

  def show
    @designer = Designer.find(params[:id])
  end


  # form to create booking
  def new
    @designer = Designer.find(params[:format])
    @booking = Booking.new
  end

 #save booking
  def create
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id
    @booking.designer_id = params[:designer]
    @booking.status = "designing"
    @booking.save
    redirect_to user_dashboard_path
  end

  def user_dashboard
    @bookings = Booking.where(user_id: current_user.id)
  end

  def designer_dashboard
    @bookings = Booking.where(designer_id: current_user.designer.id)
  end

  def model
  end

  def model_checkout

  end

  def spec

  end
  private
  def booking_params
    params.require(:booking).permit(:spec_text, :spec_file, :designer)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user

    if @message.save
      # redirect_to chatroom_path(@chatroom)

      ChatroomChannel.broadcast_to(
        @chatroom,
        message: render_to_string(partial: "message", locals: { message: @message }),
        sender_id: @message.user.id
      )
      head :ok
    else
      render "chatrooms/show", status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  # beautiful landing page, has link to #design page
  def home
  end

  # promts user to choose between custom and preset designs
  def design
  end

  # contains items added by the user
  def basket
    @cart = current_user.cart || Cart.create(user_id: current_user.id)
    params.delete(:controller)
    params.delete(:action)
    cart_items = []
    params.each do | key, value|
      cart_items << CartItem.create!(cart_id: @cart.id, quantity: value.to_i, item_id: Item.find(key.to_i).id)
    end
    @cart_items = cart_items.reject {|cart_item| cart_item.quantity == 0}
  end

  def paymentdone

  end

  def custom

  end

end

app/controllers/presets_controller.rb
class PresetsController < ApplicationController

  # landing page if user selected preset designs. Promts user to choose deisgn style and room type.
  # is a form in disquise
  def styles
  end

  # display presets matched from the #styles form
  def presets
    if params[:style].present? && params[:room].present?
      sql_query = "style ILIKE :style AND room ILIKE :room"
      @presets = Preset.where(sql_query, style: "%#{params[:style]}%", room: "%#{params[:room]}%")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VirtualStyler</title>
    <%= favicon_link_tag %>
      <link rel="icon" type="image/x-icon" href="/favicon.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/basket.html.erb
<div class="container px-0 vh-100">
  <legend class="style-legend">
    <a href="javascript:history.back()">
      <span class="greyed-out">Pick a style </span>
    </a>
    <span class="greyed-in">> </span>
    <a href="javascript:history.back()">
      <span class="greyed-out">Pick a room</span>
    </a>
    <span class="greyed-in">> </span>
    <a href="javascript:history.back()">
      <span class="greyed-out">Pick a design</span>
    </a>
    <span class="greyed-in">> Payment</span>

  </legend>
  <h2 class="pt-4">Payment</h2>

  <div class="card-body">
    <div class="row upper"></div>

    <div class="row mb-5">
      <div class="col-12 col-lg-6 mb-5 order-2 order-lg-1 ps-0 pe-2">
        <div class="payment-right" style="position: relative;">
          <h3>Order Summary</h3>
          <div class="row item preset-items-basket" style="margin-left: 0px;">            <div data-controller="basket-sum">
              <%@cart_items.each do |cart_item|%>
                <div class="d-flex item-card align-items-center mb-2" data-basket-sum-target="sum">
                  <%= cl_image_tag cart_item.item.photo.key, :width=>80,:height=>80, :crop=>"fill", class: "item-image p-2"  %>
                  <p class="mt-3 me-5 ps-2">
                    <span class="item-name"><%= cart_item.item.name %></span>
                    <br>
                    <span class="item-description"><%= cart_item.item.description %></span>
                  </p>
                  <div class="cart-input ms-auto me-5 mb-3 d-flex flex-column">
                    <div class="d-flex ">
                      <div>x<span data-basket-sum-target="quantity"><%= cart_item.quantity %></span></div>
                    </div>
                    <p class="item-price">$<span data-basket-sum-target="price"><%=cart_item.item.price%></span></p>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <div class="payment-total d-flex flex-column justify-content-end card_prire_bottun_2"><div>Your total is: $<span id="sum"></span></div></div>

        </div>
      </div>

      <div class="col-12 col-lg-6 mb-5 order-1 order-lg-2 d-flex ps-2 pe-0">
        <div class="box1">
          <div>
            <h3>Payment</h3>
            <div class="icons">
              <img src="https://img.icons8.com/color/48/000000/visa.png"/>
              <img src="https://img.icons8.com/color/48/000000/mastercard-logo.png"/>
              <img src="https://img.icons8.com/color/48/000000/maestro.png"/>
            </div>


            <form class="mt-4">
              <div>
                <span>Cardholder's name:</span>
                <input class="pay-fild" placeholder="Linda Williams">
                <span>Card Number:</span>
                <input class="pay-fild" placeholder="0125 6780 4567 9909">
                <div class="row">
                  <div class="col-4 expiry-date">
                    <span>Expiry date:</span>
                    <input class="pay-fild" placeholder="YY/MM">
                  </div>
                  <div class="col-4">
                    <span>CVV:</span>
                    <input class="pay-fild" id="cvv">
                  </div>
                </div>
                <div>
                  <input class="pay-fild" type="checkbox" id="save_card" class="align-left">
                  <label for="save_card">Save card details to wallet</label>
                </div>
              </div>
                <div>
                <div class="d-flex flex-column justify-content-end vh-20">
                  <%= link_to "Confirm payment", paymentdone_path, class: "button button-div-basket" %>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/custom.html.erb
    <div id="holder">

        <div id="model">
        <h1 class="custom-title">Coming soon...</h1>
      <model-viewer src="https://res.cloudinary.com/dxgkclowd/image/upload/v1678428698/white_modern_living_room_rxi2cr.glb" ar ar-modes="webxr scene-viewer quick-look" camera-controls poster="poster.webp" shadow-intensity="1" camera-orbit="94deg 84.33deg 21.04m" field-of-view="16.58deg" auto-rotate>
          <div class="progress-bar hide" slot="progress-bar">
        <div class="update-bar"></div>
          </div>
      </model-viewer>



        </div>
    </div>

    <!-- Loads model-viewer for modern browsers -->
    <script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.js"></script>
    <!-- Loads model-viewer for older browsers -->

app/views/pages/design.html.erb
<div class="design-page-container">
    <div class="left-choice">
      <div class="info-box">
          <h1 class ="choice-h1">Custom Design</h1>
        <div class="list-and-text">
            <ul class="design-page-list">
              <li><i class="fa-solid fa-eye"></i>   Expert knowledge</li>
              <li><i class="fa-solid fa-pen-ruler"></i>   Custom recommendations</li>
              <li><i class="fa-solid fa-address-book"></i>   Access to suppliers</li>
              <li><i class="fa-solid fa-chess-queen"></i>   Unique </li>
              <li><i class="fa-solid fa-wand-magic-sparkles"></i>   High-quality </li>
            </ul>
            <p class="design-page-description">While pre-designed spaces can be a great starting point, they do have their limitations. That's where the advantages of using a professional interior designer come in. An interior designer can bring a wealth of knowledge and expertise to a project, helping to create a truly customized and personalized space that reflects the unique personality and style of the client. Interior designers have an eye for detail and can make recommendations for furniture, accessories, and finishes that users may not have considered. </p>
        </div>
        <div class="button-div">
          <%= link_to "Choose a Designer", customs_path, class: "button" %>
        </div>
      </div>
    </div>

    <div class="right-choice">
      <div class="info-box">
          <h1 class ="choice-h1">HandPicked for you</h1>
        <div class="list-and-text">
            <ul class="design-page-list">
              <li><i class="fa-solid fa-hourglass-half"></i>   Save time</li>
              <li><i class="fa-solid fa-lightbulb"></i>   We do the thinking</li>
              <li><i class="fa-solid fa-piggy-bank"></i>   Affordable</li>
              <li><i class="fa-solid fa-chess-queen"></i>   Cohesive look </li>
              <li><i class="fa-solid fa-wand-magic-sparkles"></i>   High-quality </li>
            </ul>
            <p class="design-page-description">One of the main advantages of offering users a choice between a multitude of pre-designed spaces is that it saves them time and effort. Not everyone has the time or expertise to design their own space from scratch, and having pre-designed spaces to choose from allows them to quickly and easily find a style that suits their tastes and needs. Pre-designed spaces also provide users with inspiration and ideas, helping them to envision the possibilities for their own space. Additionally, pre-designed spaces can help users avoid costly mistakes by ensuring that the furniture and accessories they choose are complementary and cohesive.</p>
        </div>

        <div class="button-div">
          <%= link_to "Pick a Style", styles_path, class: "button" %>
        </div>

      </div>
    </div>


</div>

app/views/pages/home.html.erb
<div class="main-container">

  <div class="home-page-container">
    <div class="container-flex container">
      <div class="left-container">
          <h1 class="mb-2">Your personalized interior design experience.</h1>
          <p class="mb-4">Transform your space with our interior design services. Our experienced team works closely with you to create a personalized and functional design that reflects your unique style. From traditional to modern, we offer a range of design options to suit your preferences. Contact us today to start creating the home of your dreams!</p>
          <div>
            <%= link_to "Launch Styler", design_path, class: "button" %>
          </div>
      </div>

      
    </div>
  </div>

  <div class="container">
    <div class="row">

      <div class="col-lg-4 col-md-5 col-sm-12">
        <%= image_tag asset_path("custom-design.jpg"), class: "section-img" %>
      </div>

      <div class="col-lg-8 col-md-7 col-sm-12">
        <div class="about-container1">
          <div class="about-text">
            <h2>HandPicked for you</h2>
            <p>One of the main advantages of offering users a choice between a multitude of pre-designed spaces is that it saves them time and effort. Not everyone has the time or expertise to design their own space from scratch, and having pre-designed spaces to choose from allows them to quickly and easily find a style that suits their tastes and needs. Pre-designed spaces also provide users with inspiration and ideas, helping them to envision the possibilities for their own space. Additionally, pre-designed spaces can help users avoid costly mistakes by ensuring that the furniture and accessories they choose are complementary and cohesive.</p>
            <div class="button-div">
            <%= link_to "Launch Styler", design_path, class: "button" %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row home-row-2 mt-5 mb-5">
      <div class="col-lg-8 col-md-7 col-sm-12 order-md-1 order-sm-2">
        <div class="about-container1">
          <div class="about-text">
            <h2>Custom Design</h2>
            <p>One of the main advantages of offering users a choice between a multitude of pre-designed spaces is that it saves them time and effort. Not everyone has the time or expertise to design their own space from scratch, and having pre-designed spaces to choose from allows them to quickly and easily find a style that suits their tastes and needs. Pre-designed spaces also provide users with inspiration and ideas, helping them to envision the possibilities for their own space. Additionally, pre-designed spaces can help users avoid costly mistakes by ensuring that the furniture and accessories they choose are complementary and cohesive.</p>
            <div class="button-div">
              <%= link_to "Launch Styler", design_path, class: "button" %>
            </div>
          </div>
        </div>
      </div>

      <div class="col-lg-4 col-md-5 col-sm-12 order-md-2 order-sm-1">
            <%= image_tag asset_path("handcrafted.png"), class: "section-img" %>
      </div>
    </div>
    </div>


    <div class="footer-container">
      <div class="container footer">
        <div class="row">
          <div class="col-6">
            <p class="quote">
              At our interior design services, we believe that a well-designed space can transform your quality of life. Contact us today to learn more about how we can help you create the perfect space for your lifestyle and needs.
            </p>
          </div>
          <div class="col-6 d-flex justify-content-end align-items-start">
            <form action="/">
              <h4 class="mb-4">Join our Newsletter</h4>
              <input type="text" class="padding-input rounded" placeholder="Enter your email">
              <input type="submit" class="button">
            </form>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/pages/paymentdone.html.erb
<div class="centered-text-congrats">
  <h4>Congratulations ! Your order is being processed</h4>
    <div>
      <a class="button" href="/">Go back to homepage</a>
    </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-omar  navbar-lewagon">
  <% if action_name == "home" || action_name == "design" || action_name == "paymentdone" %>
    <div class="w-100 px-3 d-flex justify-content-between">
  <% else %>
   <div class="container p-0">
  <% end %>
    <%= link_to root_path, class: "navbar-brand" do %>
      <%="Virtual Styler"%>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

        <% if user_signed_in? %>
          <% if current_user.designer == nil %>
          <li class="nav-item active">
            <%= link_to "Dashboard", user_dashboard_path, class: "nav-link" %>
          </li>
          <% else %>
            <li class="nav-item active">
            <%= link_to "Dashboard", designer_dashboard_path, class: "nav-link" %>
          </li>
          <% end %>


          <li class="nav-item">
            <%= link_to "About", "#", class: "nav-link" %>
          </li>

          <li class="nav-item active">
              <%= link_to "FAQ", "#", class: "nav-link" %>
          </li>

          <li class="nav-item dropdown">
              <% if current_user.avatar.key.nil?%>
                <%= image_tag "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1180&q=80", height: 41, width: 50, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
                <%= cl_image_tag current_user.avatar.key, height: 410, width: 500, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
              <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", "#", class: "dropdown-item" %>
              <%= link_to " Contact us", "#", class: "dropdown-item" %>
              <%= link_to " Terms of use & Privacy Policy", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>

        <% else %>
          <li class="nav-item active">
              <%= link_to "About", "#", class: "nav-link" %>
          </li>

          <li class="nav-item active">
              <%= link_to "FAQ", "#", class: "nav-link" %>
          </li>

          <li class="nav-item">
              <%= link_to "Sign-up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>